repos:

-   repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
    - id: black
      args: [--target-version=py312, --line-length=120]
      language_version: python3.12

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    - id: mypy
      args: [
        --enable-incomplete-feature=NewGenericSyntax, # type alias 'type' introduced in 3.12
        --ignore-missing-imports,
        --strict,
        --allow-untyped-decorators, # relax --strict. @pytest.fixture
        --allow-subclassing-any,    # relax --strict.
        --show-error-codes
      ]
      additional_dependencies: ['types-PyYAML']

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-use-type-annotations

-   repo: https://github.com/pylint-dev/pylint
    rev: v3.2.6
    hooks:
    - id: pylint
      exclude: 'tests'
      args: [
        --max-line-length=120,
        --disable=design,
        --disable=missing-docstring,
        --disable=useless-super-delegation,
        --disable=import-error,
        --disable=logging-fstring-interpolation,
        --disable=invalid-name,
        --disable=duplicate-code,
        --disable=broad-except,
        --disable=logging-format-interpolation,
        --disable=too-many-lines
      ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      args: [--max-line-length=120, '--ignore=E203,W503']
