language: python

python:
  - "3.12.6"

env:
  - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR/scripts

install:
  - pip install -r requirements.txt
  - pip install pre-commit

script:
  - pre-commit run --all-files
  - pytest -vvv
